-- ============================================================================
-- Threshold — demo seed. GENERATED by scripts/generate-seed-sql.ts; do not edit.
-- Session times are placed relative to now() on real open days for each Guide.
-- Demo logins (password: threshold): ines@threshold.demo (client), mara@threshold.demo (Guide)
-- ============================================================================

begin;

-- Demo accounts ---------------------------------------------------------------
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new)
values ('00000000-0000-0000-0000-000000000000', '00000000-0000-4000-8000-0000000000a1', 'authenticated', 'authenticated', 'ines@threshold.demo', extensions.crypt('threshold', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', jsonb_build_object('display_name', 'Inês', 'timezone', 'Europe/Lisbon'), now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('00000000-0000-4000-8000-0000000000a1', '00000000-0000-4000-8000-0000000000a1', '00000000-0000-4000-8000-0000000000a1', jsonb_build_object('sub', '00000000-0000-4000-8000-0000000000a1', 'email', 'ines@threshold.demo', 'email_verified', true), 'email', now(), now(), now())
on conflict do nothing;
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new)
values ('00000000-0000-0000-0000-000000000000', '00000000-0000-4000-8000-0000000000b1', 'authenticated', 'authenticated', 'mara@threshold.demo', extensions.crypt('threshold', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', jsonb_build_object('display_name', 'Mara', 'timezone', 'Europe/Lisbon'), now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('00000000-0000-4000-8000-0000000000b1', '00000000-0000-4000-8000-0000000000b1', '00000000-0000-4000-8000-0000000000b1', jsonb_build_object('sub', '00000000-0000-4000-8000-0000000000b1', 'email', 'mara@threshold.demo', 'email_verified', true), 'email', now(), now(), now())
on conflict do nothing;
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new)
values ('00000000-0000-0000-0000-000000000000', '00000000-0000-4000-8000-0000000000c1', 'authenticated', 'authenticated', 'community@threshold.demo', extensions.crypt('threshold-community-seed', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', jsonb_build_object('display_name', 'Community', 'timezone', 'UTC'), now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('00000000-0000-4000-8000-0000000000c1', '00000000-0000-4000-8000-0000000000c1', '00000000-0000-4000-8000-0000000000c1', jsonb_build_object('sub', '00000000-0000-4000-8000-0000000000c1', 'email', 'community@threshold.demo', 'email_verified', true), 'email', now(), now(), now())
on conflict do nothing;
update public.profiles set role = 'guide' where id = '00000000-0000-4000-8000-0000000000b1';

-- Thresholds -----------------------------------------------------------------
insert into public.thresholds (slug, name, line, keywords, sort_order) values ('divorce', 'Finalizing a divorce', 'The legal end of a life that was shared for many years.', array['divorce', 'marriage', 'married', 'separation', 'separating', 'husband', 'wife', 'spouse', 'decree', 'ex', 'partner']::text[], 1)
on conflict (slug) do update set name = excluded.name, line = excluded.line, keywords = excluded.keywords, sort_order = excluded.sort_order;
insert into public.thresholds (slug, name, line, keywords, sort_order) values ('surgery', 'Before gender-affirming surgery', 'The last days before your body becomes more truly yours.', array['surgery', 'transition', 'gender', 'trans', 'affirming', 'top surgery', 'bottom surgery', 'operation', 'body']::text[], 2)
on conflict (slug) do update set name = excluded.name, line = excluded.line, keywords = excluded.keywords, sort_order = excluded.sort_order;
insert into public.thresholds (slug, name, line, keywords, sort_order) values ('career', 'Leaving a defining career', 'Walking away from the work that told you who you were.', array['career', 'job', 'retire', 'retiring', 'retirement', 'quit', 'resign', 'work', 'profession', 'leaving work', 'vocation']::text[], 3)
on conflict (slug) do update set name = excluded.name, line = excluded.line, keywords = excluded.keywords, sort_order = excluded.sort_order;
insert into public.thresholds (slug, name, line, keywords, sort_order) values ('empty-nest', 'Becoming an empty-nester', 'The house after the last child has gone.', array['children', 'child', 'kids', 'leaving home', 'empty', 'nest', 'parent', 'university', 'college', 'son', 'daughter']::text[], 4)
on conflict (slug) do update set name = excluded.name, line = excluded.line, keywords = excluded.keywords, sort_order = excluded.sort_order;
insert into public.thresholds (slug, name, line, keywords, sort_order) values ('release', 'The first months after release', 'Coming home from prison to a world that kept moving.', array['prison', 'release', 'released', 'incarceration', 'jail', 'parole', 'sentence', 'inside', 'custody', 'served']::text[], 5)
on conflict (slug) do update set name = excluded.name, line = excluded.line, keywords = excluded.keywords, sort_order = excluded.sort_order;
insert into public.thresholds (slug, name, line, keywords, sort_order) values ('diagnosis', 'Receiving a terminal diagnosis', 'When the future you were planning becomes a number.', array['terminal', 'diagnosis', 'diagnosed', 'cancer', 'dying', 'prognosis', 'illness', 'palliative', 'months to live', 'death']::text[], 6)
on conflict (slug) do update set name = excluded.name, line = excluded.line, keywords = excluded.keywords, sort_order = excluded.sort_order;
insert into public.thresholds (slug, name, line, keywords, sort_order) values ('fertility', 'Ending fertility treatment', 'Choosing to stop, and grieving a child who never arrived.', array['fertility', 'ivf', 'pregnancy', 'pregnant', 'embryo', 'childless', 'treatment', 'miscarriage', 'trying', 'conceive']::text[], 7)
on conflict (slug) do update set name = excluded.name, line = excluded.line, keywords = excluded.keywords, sort_order = excluded.sort_order;
insert into public.thresholds (slug, name, line, keywords, sort_order) values ('disability', 'Moving into permanent disability', 'The day a temporary situation is named permanent.', array['disability', 'disabled', 'wheelchair', 'chronic', 'injury', 'mobility', 'sight', 'hearing', 'paralysis', 'permanent', 'accident']::text[], 8)
on conflict (slug) do update set name = excluded.name, line = excluded.line, keywords = excluded.keywords, sort_order = excluded.sort_order;
insert into public.thresholds (slug, name, line, keywords, sort_order) values ('name', 'Legally changing your name', 'Signing away the name you were given for the one you chose.', array['name', 'deed poll', 'legal name', 'rename', 'renaming', 'identity', 'surname', 'maiden']::text[], 9)
on conflict (slug) do update set name = excluded.name, line = excluded.line, keywords = excluded.keywords, sort_order = excluded.sort_order;

-- Session forms ---------------------------------------------------------------
insert into public.session_types (key, name, duration_min, line, sort_order) values ('solo', 'Solo', 90, 'Ninety minutes. You and your Guide, and nothing else in the room.', 1)
on conflict (key) do update set name = excluded.name, duration_min = excluded.duration_min, line = excluded.line, sort_order = excluded.sort_order;
insert into public.session_types (key, name, duration_min, line, sort_order) values ('witnessed', 'Witnessed', 120, 'Bring one person to stand beside you. They witness; they do not have to speak.', 2)
on conflict (key) do update set name = excluded.name, duration_min = excluded.duration_min, line = excluded.line, sort_order = excluded.sort_order;
insert into public.session_types (key, name, duration_min, line, sort_order) values ('aftermath', 'Threshold + Practical Aftermath', 150, 'Ninety minutes held, then an hour on what must be done next — the forms, the calls, the words for other people.', 3)
on conflict (key) do update set name = excluded.name, duration_min = excluded.duration_min, line = excluded.line, sort_order = excluded.sort_order;

-- Guides, their thresholds and weekly availability -------------------------------
insert into public.guides (id, user_id, slug, name, pronouns, presence, statement, background, location, timezone, years_holding, tags, languages, max_sessions_per_day)
values ('10000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-0000000000b1', 'mara', 'Mara Okafor-Lindqvist', 'she/her', 'still', 'I won''t tell you it will be fine. I''ll stay in the room while it is enormous.', 'Fourteen years as a hospice chaplain in Gothenburg and Lisbon.', 'Lisbon', 'Europe/Lisbon', 14, array['Former hospice chaplain', 'Comfortable with long silence', 'Non-religious practice']::text[], array['English', 'Portuguese', 'Swedish']::text[], 2)
on conflict (id) do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000001', 'diagnosis') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000001', 'divorce') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000001', 'career') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000001', 'empty-nest') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000001', 'fertility') on conflict do nothing;
delete from public.availability_rules where guide_id = '10000000-0000-4000-8000-000000000001';
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000001', 1, '09:00', '18:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000001', 2, '09:00', '18:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000001', 4, '09:00', '18:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000001', 5, '09:00', '14:30');
insert into public.guides (id, user_id, slug, name, pronouns, presence, statement, background, location, timezone, years_holding, tags, languages, max_sessions_per_day)
values ('10000000-0000-4000-8000-000000000002', null, 'tobias', 'Tobias Reinholt', 'he/him', 'steady', 'Big days need a shape. I bring the shape, so you can bring everything else.', 'Eleven years in probation services, then a decade as a family mediator.', 'Berlin', 'Europe/Berlin', 10, array['Former probation officer', 'Mediator', 'Structured sessions']::text[], array['English', 'German']::text[], 2)
on conflict (id) do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000002', 'release') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000002', 'career') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000002', 'divorce') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000002', 'disability') on conflict do nothing;
delete from public.availability_rules where guide_id = '10000000-0000-4000-8000-000000000002';
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000002', 1, '08:00', '16:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000002', 2, '08:00', '16:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000002', 3, '08:00', '16:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000002', 4, '08:00', '16:00');
insert into public.guides (id, user_id, slug, name, pronouns, presence, statement, background, location, timezone, years_holding, tags, languages, max_sessions_per_day)
values ('10000000-0000-4000-8000-000000000003', null, 'imani', 'Imani Castellanos', 'they/them', 'direct', 'You don''t need to explain yourself to me. We can start where you actually are.', 'Trans peer advocate; supported hundreds of people through surgery and legal change.', 'Mexico City', 'America/Mexico_City', 8, array['Trans-led practice', 'Peer advocate', 'Plain speech']::text[], array['English', 'Spanish']::text[], 2)
on conflict (id) do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000003', 'surgery') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000003', 'name') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000003', 'release') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000003', 'disability') on conflict do nothing;
delete from public.availability_rules where guide_id = '10000000-0000-4000-8000-000000000003';
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000003', 2, '10:00', '19:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000003', 3, '10:00', '19:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000003', 4, '10:00', '19:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000003', 5, '10:00', '19:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000003', 6, '10:00', '19:00');
insert into public.guides (id, user_id, slug, name, pronouns, presence, statement, background, location, timezone, years_holding, tags, languages, max_sessions_per_day)
values ('10000000-0000-4000-8000-000000000004', null, 'ruth', 'Ruth Adeyemi', 'she/her', 'tender', 'Grief is allowed to be loud here. I have sat with a great deal of it, and I''m not afraid of yours.', 'Twenty years as a neonatal nurse, then bereavement support.', 'Toronto', 'America/Toronto', 9, array['Former NICU nurse', 'Bereavement support', 'Parents']::text[], array['English', 'Yoruba']::text[], 2)
on conflict (id) do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000004', 'fertility') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000004', 'empty-nest') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000004', 'diagnosis') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000004', 'surgery') on conflict do nothing;
delete from public.availability_rules where guide_id = '10000000-0000-4000-8000-000000000004';
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000004', 1, '09:00', '17:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000004', 3, '09:00', '17:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000004', 5, '09:00', '17:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000004', 6, '10:00', '14:30');
insert into public.guides (id, user_id, slug, name, pronouns, presence, statement, background, location, timezone, years_holding, tags, languages, max_sessions_per_day)
values ('10000000-0000-4000-8000-000000000005', null, 'soren', 'Søren Achterberg', 'he/him', 'still', 'I hold one threshold a day, in the morning, and nothing after it.', 'Became paraplegic at thirty-one. Has guided others across the same line since.', 'Melbourne', 'Australia/Melbourne', 12, array['Lived experience of disability', 'One session a day', 'Early mornings']::text[], array['English', 'Danish']::text[], 1)
on conflict (id) do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000005', 'disability') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000005', 'diagnosis') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000005', 'career') on conflict do nothing;
delete from public.availability_rules where guide_id = '10000000-0000-4000-8000-000000000005';
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000005', 1, '07:30', '13:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000005', 2, '07:30', '13:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000005', 3, '07:30', '13:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000005', 4, '07:30', '13:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000005', 5, '07:30', '13:00');
insert into public.guides (id, user_id, slug, name, pronouns, presence, statement, background, location, timezone, years_holding, tags, languages, max_sessions_per_day)
values ('10000000-0000-4000-8000-000000000006', null, 'noor', 'Noor Haddad', 'she/her', 'direct', 'I practised family law for fifteen years. I know what the paperwork does not say.', 'Former family lawyer; left practice to sit on the other side of the table.', 'New York', 'America/New_York', 6, array['Former family lawyer', 'Evening hours', 'Practical aftermath']::text[], array['English', 'Arabic', 'French']::text[], 2)
on conflict (id) do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000006', 'divorce') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000006', 'name') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000006', 'empty-nest') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000006', 'fertility') on conflict do nothing;
delete from public.availability_rules where guide_id = '10000000-0000-4000-8000-000000000006';
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000006', 1, '11:00', '20:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000006', 2, '11:00', '20:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000006', 3, '11:00', '20:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000006', 4, '11:00', '20:00');
insert into public.guides (id, user_id, slug, name, pronouns, presence, statement, background, location, timezone, years_holding, tags, languages, max_sessions_per_day)
values ('10000000-0000-4000-8000-000000000007', null, 'ash', 'Ash Delacroix-Mbeki', 'they/them', 'steady', 'I have crossed a few of these myself. I''ll walk at your pace, not mine.', 'Social worker in re-entry programmes; changed their own name at forty.', 'Nairobi', 'Africa/Nairobi', 7, array['Re-entry social worker', 'Lived experience', 'Swahili & French']::text[], array['English', 'Swahili', 'French']::text[], 2)
on conflict (id) do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000007', 'surgery') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000007', 'name') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000007', 'release') on conflict do nothing;
insert into public.guide_thresholds (guide_id, threshold_slug) values ('10000000-0000-4000-8000-000000000007', 'diagnosis') on conflict do nothing;
delete from public.availability_rules where guide_id = '10000000-0000-4000-8000-000000000007';
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000007', 1, '09:00', '17:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000007', 3, '09:00', '17:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000007', 4, '09:00', '17:00');
insert into public.availability_rules (guide_id, weekday, start_local, end_local) values ('10000000-0000-4000-8000-000000000007', 6, '09:00', '17:00');

-- Placement helper: first open day on/after (or before, for the past) an offset --
create or replace function pg_temp.seed_place(p_guide uuid, p_offset int, p_local time, p_duration int)
returns timestamptz
language plpgsql
as $$
declare
  g        public.guides%rowtype;
  v_today  date;
  v_day    date;
  v_dir    int := case when p_offset < 0 then -1 else 1 end;
  v_start  timestamptz;
begin
  select * into g from public.guides where id = p_guide;
  v_today := (now() at time zone g.timezone)::date;
  for i in 0..20 loop
    v_day := v_today + p_offset + v_dir * i;
    continue when not exists (
      select 1 from public.availability_rules r
      where r.guide_id = p_guide
        and r.weekday = extract(dow from v_day)::int
        and r.start_local <= p_local - make_interval(mins => g.buffer_min)
        and r.end_local >= p_local + make_interval(mins => p_duration + g.buffer_min)
    );
    v_start := (v_day + p_local) at time zone g.timezone;
    continue when exists (
      select 1 from public.sessions s
      where s.guide_id = p_guide and s.status <> 'cancelled'
        and s.blocked_range && tstzrange(
          v_start - make_interval(mins => g.buffer_min),
          v_start + make_interval(mins => p_duration + g.buffer_min), '[)')
    );
    continue when v_dir > 0 and v_start <= now();
    return v_start;
  end loop;
  return null;
end $$;

-- Sessions, reflective answers, letters ----------------------------------------
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-0000000000a1', '10000000-0000-4000-8000-000000000001', 'career', 'Retiring from air traffic control after twenty-six years.', 'solo', v.start, v.start + interval '90 minutes', 'Inês', 'Europe/Lisbon', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000001', -7, '10:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Twenty-six years in the tower at Humberto Delgado. My last shift is the Friday before we meet.' from public.sessions where id = '20000000-0000-4000-8000-000000000001'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to lose the version of me who is needed at 6:40 every morning. Afraid to keep the vigilance — I don''t sleep without it.' from public.sessions where id = '20000000-0000-4000-8000-000000000001'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'Please don''t congratulate me. Everyone keeps congratulating me.' from public.sessions where id = '20000000-0000-4000-8000-000000000001'
on conflict (session_id, position) do nothing;
insert into public.future_self_letters (id, session_id, client_id, body, unlocks_at, created_at)
select '30000000-0000-4000-8000-000000000001', id, client_id, 'Inês —

By the time you read this the badge will be gone, and the lanyard will be in a drawer you''ll pretend you don''t know about. Twenty-six years. You were the person who knew where every aircraft was. Now you are a person who doesn''t have to know.

Remember that you were frightened on Tuesday morning, and that you went anyway. Remember that Mara didn''t tell you it would be fine. She let it be enormous, and it was, and you were still there at the end of it.

You are allowed to miss it. You are allowed to not miss it. Both will happen, sometimes before lunch.

Go and stand at the window at 6:40, when the first departures used to come through. Just once. Then make coffee on no one''s schedule but yours.

— I.', ends_at + interval '48 hours', starts_at - interval '9 days' from public.sessions where id = '20000000-0000-4000-8000-000000000001'
on conflict (session_id) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-0000000000a1', '10000000-0000-4000-8000-000000000004', 'empty-nest', 'My youngest leaves for Edinburgh in two weeks.', 'witnessed', v.start, v.start + interval '120 minutes', 'Inês', 'Europe/Lisbon', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000004', 9, '10:00', 120) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Twenty-three years of someone coming home at the end of the day.' from public.sessions where id = '20000000-0000-4000-8000-000000000002'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', null from public.sessions where id = '20000000-0000-4000-8000-000000000002'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'My sister Lúcia will be there as my witness. She raised four; she knows.' from public.sessions where id = '20000000-0000-4000-8000-000000000002'
on conflict (session_id, position) do nothing;
insert into public.future_self_letters (id, session_id, client_id, body, unlocks_at, created_at)
select '30000000-0000-4000-8000-000000000002', id, client_id, 'To the woman in the quiet house —

You were afraid the silence would be an accusation. I hope by now it has become a room you are allowed to sit in.

Call him on Sunday, not before. Let him miss you a little.

— I.', ends_at + interval '48 hours', starts_at - interval '9 days' from public.sessions where id = '20000000-0000-4000-8000-000000000002'
on conflict (session_id) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000010', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000001', 'fertility', null, 'solo', v.start, v.start + interval '90 minutes', 'Dev', 'Europe/London', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000001', -2, '11:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Our eighth transfer. We have decided it is the last.' from public.sessions where id = '20000000-0000-4000-8000-000000000010'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to keep hoping. It has become a second job.' from public.sessions where id = '20000000-0000-4000-8000-000000000010'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', null from public.sessions where id = '20000000-0000-4000-8000-000000000010'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000011', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000001', 'diagnosis', null, 'solo', v.start, v.start + interval '90 minutes', 'Hanne', 'Europe/Copenhagen', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000001', 1, '10:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'The oncologist said months, and then she said ''probably not a year''. I keep hearing ''probably''.' from public.sessions where id = '20000000-0000-4000-8000-000000000011'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to lose the ability to plan anything at all. I''m a planner.' from public.sessions where id = '20000000-0000-4000-8000-000000000011'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'I don''t want to talk about treatment. My family does enough of that. I want to talk about what''s left that''s mine.' from public.sessions where id = '20000000-0000-4000-8000-000000000011'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000012', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000001', 'divorce', 'The decree absolute arrives this week. Nineteen years.', 'witnessed', v.start, v.start + interval '120 minutes', 'R.', 'Europe/London', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000001', 1, '14:00', 120) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Nineteen years of marriage, officially, on a piece of paper that arrives by email.' from public.sessions where id = '20000000-0000-4000-8000-000000000012'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to keep the anger. It''s the only thing that feels like him now.' from public.sessions where id = '20000000-0000-4000-8000-000000000012'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'My friend Callum is coming as witness. He was best man. He''s on my side but he loved us both.' from public.sessions where id = '20000000-0000-4000-8000-000000000012'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000013', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000001', 'fertility', null, 'aftermath', v.start, v.start + interval '150 minutes', 'Sofía', 'Europe/Madrid', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000001', 3, '11:00', 150) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Six years of injections, calendars and waiting rooms.' from public.sessions where id = '20000000-0000-4000-8000-000000000013'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to lose the future I''ve been furnishing in my head since I was thirty.' from public.sessions where id = '20000000-0000-4000-8000-000000000013'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'In the practical hour I need help with what to tell my mother. And the clinic still has two embryos.' from public.sessions where id = '20000000-0000-4000-8000-000000000013'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000014', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000001', 'career', null, 'solo', v.start, v.start + interval '90 minutes', 'Ingrid', 'Europe/Oslo', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000001', 7, '13:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Thirty-one years as a surgeon. My hands aren''t steady enough any more.' from public.sessions where id = '20000000-0000-4000-8000-000000000014'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to lose being the person in the room who knows what to do.' from public.sessions where id = '20000000-0000-4000-8000-000000000014'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'I will probably be very composed. It isn''t how I feel.' from public.sessions where id = '20000000-0000-4000-8000-000000000014'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000015', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000001', 'diagnosis', null, 'witnessed', v.start, v.start + interval '120 minutes', 'Jonah', 'America/New_York', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000001', 10, '10:00', 120) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'ALS. I told my kids on Sunday.' from public.sessions where id = '20000000-0000-4000-8000-000000000015'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', null from public.sessions where id = '20000000-0000-4000-8000-000000000015'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'My brother Eli will be there. I talk slowly now; please wait for me.' from public.sessions where id = '20000000-0000-4000-8000-000000000015'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000020', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000002', 'release', null, 'solo', v.start, v.start + interval '90 minutes', 'Marcus', 'America/Chicago', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000002', 2, '09:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Eleven years inside. Out on the 3rd.' from public.sessions where id = '20000000-0000-4000-8000-000000000020'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to lose the routine. Afraid to keep the way I watch doors.' from public.sessions where id = '20000000-0000-4000-8000-000000000020'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', null from public.sessions where id = '20000000-0000-4000-8000-000000000020'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000021', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000002', 'career', null, 'aftermath', v.start, v.start + interval '150 minutes', 'Petra', 'Europe/Vienna', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000002', 5, '12:00', 150) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Closing the bakery my grandfather opened.' from public.sessions where id = '20000000-0000-4000-8000-000000000021'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to keep the guilt.' from public.sessions where id = '20000000-0000-4000-8000-000000000021'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'Please help me write the notice for the window.' from public.sessions where id = '20000000-0000-4000-8000-000000000021'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000022', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000002', 'divorce', null, 'witnessed', v.start, v.start + interval '120 minutes', 'Lena', 'Europe/Berlin', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000002', 11, '09:30', 120) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Twelve years.' from public.sessions where id = '20000000-0000-4000-8000-000000000022'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', null from public.sessions where id = '20000000-0000-4000-8000-000000000022'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'My daughter (22) will witness.' from public.sessions where id = '20000000-0000-4000-8000-000000000022'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000023', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000003', 'name', null, 'solo', v.start, v.start + interval '90 minutes', 'Kit', 'America/Los_Angeles', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000003', 2, '12:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'The name my parents chose.' from public.sessions where id = '20000000-0000-4000-8000-000000000023'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to keep the flinch when someone says it.' from public.sessions where id = '20000000-0000-4000-8000-000000000023'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', null from public.sessions where id = '20000000-0000-4000-8000-000000000023'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000024', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000003', 'surgery', null, 'solo', v.start, v.start + interval '90 minutes', 'Theo', 'America/Mexico_City', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000003', 6, '15:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Surgery on the 14th.' from public.sessions where id = '20000000-0000-4000-8000-000000000024'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid I''ll feel nothing and that will mean something.' from public.sessions where id = '20000000-0000-4000-8000-000000000024'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'I''m fine with swearing.' from public.sessions where id = '20000000-0000-4000-8000-000000000024'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000025', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000003', 'surgery', null, 'witnessed', v.start, v.start + interval '120 minutes', 'Ari', 'America/Bogota', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000003', 10, '11:00', 120) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Waiting eight years for this date.' from public.sessions where id = '20000000-0000-4000-8000-000000000025'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', null from public.sessions where id = '20000000-0000-4000-8000-000000000025'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'My partner will be there.' from public.sessions where id = '20000000-0000-4000-8000-000000000025'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000026', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000004', 'fertility', null, 'solo', v.start, v.start + interval '90 minutes', 'Claire', 'America/Toronto', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000004', 3, '10:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'We''re stopping.' from public.sessions where id = '20000000-0000-4000-8000-000000000026'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to lose my marriage too.' from public.sessions where id = '20000000-0000-4000-8000-000000000026'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', null from public.sessions where id = '20000000-0000-4000-8000-000000000026'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000027', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000004', 'diagnosis', null, 'solo', v.start, v.start + interval '90 minutes', 'Paul', 'America/Vancouver', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000004', 12, '13:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Stage four.' from public.sessions where id = '20000000-0000-4000-8000-000000000027'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to keep pretending for my wife.' from public.sessions where id = '20000000-0000-4000-8000-000000000027'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'I cry easily. Don''t mind it.' from public.sessions where id = '20000000-0000-4000-8000-000000000027'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000028', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000005', 'disability', null, 'solo', v.start, v.start + interval '90 minutes', 'Grace', 'Australia/Sydney', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000005', 1, '09:30', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'The specialist wrote ''permanent''.' from public.sessions where id = '20000000-0000-4000-8000-000000000028'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to lose running. It was how I thought.' from public.sessions where id = '20000000-0000-4000-8000-000000000028'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', null from public.sessions where id = '20000000-0000-4000-8000-000000000028'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000029', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000005', 'career', null, 'solo', v.start, v.start + interval '90 minutes', 'Hamish', 'Australia/Melbourne', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000005', 4, '08:30', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Forty years on the farm. Selling it.' from public.sessions where id = '20000000-0000-4000-8000-000000000029'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', null from public.sessions where id = '20000000-0000-4000-8000-000000000029'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'I''m not much of a talker.' from public.sessions where id = '20000000-0000-4000-8000-000000000029'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000030', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000005', 'diagnosis', null, 'solo', v.start, v.start + interval '90 minutes', 'Wen', 'Asia/Singapore', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000005', 8, '09:30', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Motor neurone disease.' from public.sessions where id = '20000000-0000-4000-8000-000000000030'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to lose my voice before I''ve said things.' from public.sessions where id = '20000000-0000-4000-8000-000000000030'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', null from public.sessions where id = '20000000-0000-4000-8000-000000000030'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000031', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000006', 'divorce', null, 'aftermath', v.start, v.start + interval '150 minutes', 'Dana', 'America/New_York', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000006', 2, '12:00', 150) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Signing on Thursday.' from public.sessions where id = '20000000-0000-4000-8000-000000000031'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to keep his last name.' from public.sessions where id = '20000000-0000-4000-8000-000000000031'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'Practical hour: the name change and the kids'' school forms.' from public.sessions where id = '20000000-0000-4000-8000-000000000031'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000032', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000006', 'name', null, 'solo', v.start, v.start + interval '90 minutes', 'Priya', 'America/Chicago', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000006', 4, '15:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'My father''s name.' from public.sessions where id = '20000000-0000-4000-8000-000000000032'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', null from public.sessions where id = '20000000-0000-4000-8000-000000000032'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', null from public.sessions where id = '20000000-0000-4000-8000-000000000032'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000033', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000006', 'fertility', null, 'solo', v.start, v.start + interval '90 minutes', 'Mel', 'America/Denver', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000006', 13, '17:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Ten years of trying.' from public.sessions where id = '20000000-0000-4000-8000-000000000033'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to lose my body''s purpose, as I understood it.' from public.sessions where id = '20000000-0000-4000-8000-000000000033'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', null from public.sessions where id = '20000000-0000-4000-8000-000000000033'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000034', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000007', 'surgery', null, 'solo', v.start, v.start + interval '90 minutes', 'Zawadi', 'Africa/Nairobi', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000007', 3, '10:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Surgery in Bangkok next month.' from public.sessions where id = '20000000-0000-4000-8000-000000000034'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to keep hiding.' from public.sessions where id = '20000000-0000-4000-8000-000000000034'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', null from public.sessions where id = '20000000-0000-4000-8000-000000000034'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000035', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000007', 'release', null, 'aftermath', v.start, v.start + interval '150 minutes', 'Omar', 'Africa/Cairo', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000007', 6, '13:00', 150) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'Seven years.' from public.sessions where id = '20000000-0000-4000-8000-000000000035'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', null from public.sessions where id = '20000000-0000-4000-8000-000000000035'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', 'Practical hour: ID documents and a bank account.' from public.sessions where id = '20000000-0000-4000-8000-000000000035'
on conflict (session_id, position) do nothing;
insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select '20000000-0000-4000-8000-000000000036', '00000000-0000-4000-8000-0000000000c1', '10000000-0000-4000-8000-000000000007', 'name', null, 'solo', v.start, v.start + interval '90 minutes', 'Jules', 'Europe/Paris', least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place('10000000-0000-4000-8000-000000000007', 15, '11:00', 90) as start) v
where v.start is not null
on conflict (id) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 1, 'What is ending?', 'My deadname.' from public.sessions where id = '20000000-0000-4000-8000-000000000036'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 2, 'What are you afraid to lose — or afraid to keep?', 'Afraid to lose my grandmother''s way of saying it.' from public.sessions where id = '20000000-0000-4000-8000-000000000036'
on conflict (session_id, position) do nothing;
insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, 3, 'What should your Guide know before you arrive?', null from public.sessions where id = '20000000-0000-4000-8000-000000000036'
on conflict (session_id, position) do nothing;

commit;
