/**
 * Renders src/lib/data/seed.ts into supabase/seed.sql so the Supabase project and
 * the in-browser demo store share one source of truth.
 *
 *   npm run seed:sql
 */
import { writeFileSync } from "node:fs";
import {
  DEMO_USERS,
  REFLECTIVE_PROMPTS,
  SEED_GUIDES,
  SEED_SESSIONS,
  SEED_SESSION_TYPES,
  SEED_THRESHOLDS,
} from "../src/lib/data/seed.ts";

const q = (v: string | null | undefined) => (v == null ? "null" : `'${v.replace(/'/g, "''")}'`);
const arr = (xs: readonly string[]) => `array[${xs.map(q).join(", ")}]::text[]`;
const out: string[] = [];
const line = (s = "") => out.push(s);

line("-- ============================================================================");
line("-- Threshold — demo seed. GENERATED by scripts/generate-seed-sql.ts; do not edit.");
line("-- Session times are placed relative to now() on real open days for each Guide.");
line("-- Demo logins (password: threshold): ines@threshold.demo (client), mara@threshold.demo (Guide)");
line("-- ============================================================================");
line();
line("begin;");
line();

line("-- Demo accounts ---------------------------------------------------------------");
for (const u of Object.values(DEMO_USERS)) {
  line(`insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new)
values ('00000000-0000-0000-0000-000000000000', ${q(u.id)}, 'authenticated', 'authenticated', ${q(u.email)}, extensions.crypt(${q(u.password)}, extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', jsonb_build_object('display_name', ${q(u.display_name)}, 'timezone', ${q(u.timezone)}), now(), now(), '', '', '', '')
on conflict (id) do nothing;`);
  line(`insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (${q(u.id)}, ${q(u.id)}, ${q(u.id)}, jsonb_build_object('sub', ${q(u.id)}, 'email', ${q(u.email)}, 'email_verified', true), 'email', now(), now(), now())
on conflict do nothing;`);
}
line(`update public.profiles set role = 'guide' where id = ${q(DEMO_USERS.guide.id)};`);
line();

line("-- Thresholds -----------------------------------------------------------------");
for (const t of SEED_THRESHOLDS) {
  line(`insert into public.thresholds (slug, name, line, keywords, sort_order) values (${q(t.slug)}, ${q(t.name)}, ${q(t.line)}, ${arr(t.keywords)}, ${t.sort_order})
on conflict (slug) do update set name = excluded.name, line = excluded.line, keywords = excluded.keywords, sort_order = excluded.sort_order;`);
}
line();

line("-- Session forms ---------------------------------------------------------------");
for (const t of SEED_SESSION_TYPES) {
  line(`insert into public.session_types (key, name, duration_min, line, sort_order) values (${q(t.key)}, ${q(t.name)}, ${t.duration_min}, ${q(t.line)}, ${t.sort_order})
on conflict (key) do update set name = excluded.name, duration_min = excluded.duration_min, line = excluded.line, sort_order = excluded.sort_order;`);
}
line();

line("-- Guides, their thresholds and weekly availability -------------------------------");
for (const g of SEED_GUIDES) {
  line(`insert into public.guides (id, user_id, slug, name, pronouns, presence, statement, background, location, timezone, years_holding, tags, languages, max_sessions_per_day)
values (${q(g.id)}, ${q(g.user_id)}, ${q(g.slug)}, ${q(g.name)}, ${q(g.pronouns)}, ${q(g.presence)}, ${q(g.statement)}, ${q(g.background)}, ${q(g.location)}, ${q(g.timezone)}, ${g.years_holding}, ${arr(g.tags)}, ${arr(g.languages)}, ${g.max_sessions_per_day})
on conflict (id) do nothing;`);
  for (const t of g.thresholds) {
    line(`insert into public.guide_thresholds (guide_id, threshold_slug) values (${q(g.id)}, ${q(t)}) on conflict do nothing;`);
  }
  line(`delete from public.availability_rules where guide_id = ${q(g.id)};`);
  for (const [wd, start, end] of g.availability) {
    line(`insert into public.availability_rules (guide_id, weekday, start_local, end_local) values (${q(g.id)}, ${wd}, ${q(start)}, ${q(end)});`);
  }
}
line();

line("-- Placement helper: first open day on/after (or before, for the past) an offset --");
line(`create or replace function pg_temp.seed_place(p_guide uuid, p_offset int, p_local time, p_duration int)
returns timestamptz
language plpgsql
as $$
declare
  g        public.guides%rowtype;
  v_today  date;
  v_day    date;
  v_dir    int := case when p_offset < 0 then -1 else 1 end;
  v_start  timestamptz;
begin
  select * into g from public.guides where id = p_guide;
  v_today := (now() at time zone g.timezone)::date;
  for i in 0..20 loop
    v_day := v_today + p_offset + v_dir * i;
    continue when not exists (
      select 1 from public.availability_rules r
      where r.guide_id = p_guide
        and r.weekday = extract(dow from v_day)::int
        and r.start_local <= p_local - make_interval(mins => g.buffer_min)
        and r.end_local >= p_local + make_interval(mins => p_duration + g.buffer_min)
    );
    v_start := (v_day + p_local) at time zone g.timezone;
    continue when exists (
      select 1 from public.sessions s
      where s.guide_id = p_guide and s.status <> 'cancelled'
        and s.blocked_range && tstzrange(
          v_start - make_interval(mins => g.buffer_min),
          v_start + make_interval(mins => p_duration + g.buffer_min), '[)')
    );
    continue when v_dir > 0 and v_start <= now();
    return v_start;
  end loop;
  return null;
end $$;`);
line();

line("-- Sessions, reflective answers, letters ----------------------------------------");
for (const s of SEED_SESSIONS) {
  const guide = SEED_GUIDES.find((g) => g.slug === s.guide)!;
  const type = SEED_SESSION_TYPES.find((t) => t.key === s.session_type)!;
  const client = s.client === "client" ? DEMO_USERS.client.id : DEMO_USERS.community.id;
  line(`insert into public.sessions (id, client_id, guide_id, threshold_slug, threshold_words, session_type, starts_at, ends_at, client_name, client_timezone, created_at)
select ${q(s.id)}, ${q(client)}, ${q(guide.id)}, ${q(s.threshold_slug)}, ${q(s.threshold_words)}, ${q(s.session_type)}, v.start, v.start + interval '${type.duration_min} minutes', ${q(s.client_name)}, ${q(s.client_timezone)}, least(now(), v.start) - interval '12 days'
from (select pg_temp.seed_place(${q(guide.id)}, ${s.day_offset}, ${q(s.local_time)}, ${type.duration_min}) as start) v
where v.start is not null
on conflict (id) do nothing;`);
  s.answers.forEach((a, i) => {
    line(`insert into public.reflective_answers (session_id, client_id, position, prompt, answer)
select id, client_id, ${i + 1}, ${q(REFLECTIVE_PROMPTS[i].prompt)}, ${q(a)} from public.sessions where id = ${q(s.id)}
on conflict (session_id, position) do nothing;`);
  });
  if (s.letter) {
    line(`insert into public.future_self_letters (id, session_id, client_id, body, unlocks_at, created_at)
select ${q(s.id.replace(/^2/, "3"))}, id, client_id, ${q(s.letter)}, ends_at + interval '48 hours', starts_at - interval '9 days' from public.sessions where id = ${q(s.id)}
on conflict (session_id) do nothing;`);
  }
}
line();
line("commit;");

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n") + "\n");
console.log(`supabase/seed.sql written (${SEED_SESSIONS.length} sessions, ${SEED_GUIDES.length} guides).`);
