/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IFernhillEscrow {
    function deposit(bytes32 id, uint256 amount, uint64 start_time) external;

    function cancelFree(bytes32 id) external;

    function refund(bytes32 id) external;

    function capture(bytes32 id) external;

    function complete(bytes32 id) external;

    function reschedule(bytes32 id, uint64 new_start) external;

    function reclaim(bytes32 id) external;

    function booking(bytes32 id) external view returns (address, uint256, uint64, uint8);

    function owner() external view returns (address);

    function token() external view returns (address);

    error NotOwner();

    error NotCustomer();

    error AlreadyInitialised();

    error ZeroAmount();

    error StartInPast();

    error AlreadyExists();

    error NotHeld();

    error FreeWindowClosed();

    error FreeWindowStillOpen();

    error JobNotStarted();

    error TooEarlyToReclaim();

    error BadReschedule();

    error TransferFailed();
}
